from __future__ import annotations

import ast
import csv
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ERRORS: list[str] = []

REQUIRED_ROOT_FILES = [
    ".editorconfig",
    ".gitattributes",
    ".gitignore",
    "README.md",
    "SYSTEM.md",
    "AGENTS.md",
    "CLAUDE.md",
    "ANTIGRAVITY.md",
    "OPENCODE.md",
    "COPENCODE.md",
    "CHANGELOG.md",
    "CODE_OF_CONDUCT.md",
    "CONTRIBUTING.md",
    "LICENSE",
    "Makefile",
    "SECURITY.md",
    "SUPPORT.md",
    "compose.odoo.yml",
    "pyproject.toml",
    "docs/cli.md",
    "docs/install-and-use.md",
    "docs/publishing.md",
    "docs/public-release-checklist.md",
    "docs/vision.md",
]

REQUIRED_SCRIPT_FILES = [
    "scripts/validate.ps1",
    "scripts/validate.sh",
    "scripts/test.ps1",
    "scripts/test.sh",
    "scripts/odoo-smoke-test.ps1",
    "scripts/odoo-smoke-test.sh",
]

REQUIRED_CLI_FILES = [
    "src/odoo_architect_cli/__init__.py",
    "src/odoo_architect_cli/__main__.py",
    "src/odoo_architect_cli/cli.py",
    "src/odoo_architect_cli/paths.py",
    "src/odoo_architect_cli/review.py",
    "src/odoo_architect_cli/scaffold.py",
    "tests/__init__.py",
    "tests/unit/__init__.py",
    "tests/unit/test_cli.py",
]

REQUIRED_ADAPTER_FILES = [
    ".codex/skills/odoo-architect/SKILL.md",
    ".agents/skills/odoo-architect/SKILL.md",
    ".agents/rules/odoo-architect.md",
    ".agents/agents/odoo-architect/agent.md",
    ".agents/workflows/create-odoo-module.md",
    ".opencode/agents/odoo-architect.md",
    ".claude/commands/odoo-module.md",
    ".github/PULL_REQUEST_TEMPLATE.md",
    ".github/ISSUE_TEMPLATE/bug_report.md",
    ".github/ISSUE_TEMPLATE/feature_request.md",
    ".github/ISSUE_TEMPLATE/config.yml",
]

REQUIRED_FRAMEWORK_DIRS = [
    "system",
    "skills",
    "workflows",
    "templates",
    "patterns",
    "industries",
    "checklists",
    "integrations",
    "docs",
    "scripts",
    "tools",
    "src",
    "tests",
    "examples/custom_addons",
]

MANIFEST_REQUIRED_KEYS = {
    "name",
    "version",
    "summary",
    "depends",
    "data",
    "license",
    "installable",
}

ACCESS_HEADER = [
    "id",
    "name",
    "model_id:id",
    "group_id:id",
    "perm_read",
    "perm_write",
    "perm_create",
    "perm_unlink",
]


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def fail(message: str) -> None:
    ERRORS.append(message)


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def check_required_files() -> None:
    for name in (
        REQUIRED_ROOT_FILES
        + REQUIRED_SCRIPT_FILES
        + REQUIRED_CLI_FILES
        + REQUIRED_ADAPTER_FILES
    ):
        path = ROOT / name
        if not path.is_file():
            fail(f"Missing required file: {name}")
            continue
        if not read_text(path).strip():
            fail(f"Required file is empty: {name}")

    for name in REQUIRED_FRAMEWORK_DIRS:
        path = ROOT / name
        if not path.is_dir():
            fail(f"Missing required directory: {name}")


def check_cross_platform_scripts() -> None:
    for name in ["scripts/validate.sh", "scripts/test.sh", "scripts/odoo-smoke-test.sh"]:
        path = ROOT / name
        if not path.is_file():
            continue
        content = path.read_bytes()
        if not content.startswith(b"#!/usr/bin/env bash\n"):
            fail(f"Shell script must use bash shebang and LF newline: {name}")
        if b"\r\n" in content:
            fail(f"Shell script must use LF line endings: {name}")

    for name in [
        "scripts/validate.ps1",
        "scripts/test.ps1",
        "scripts/odoo-smoke-test.ps1",
    ]:
        path = ROOT / name
        if not path.is_file():
            continue
        text = read_text(path)
        if "$ErrorActionPreference = \"Stop\"" not in text:
            fail(f"PowerShell script must fail fast: {name}")


def check_cli_package_metadata() -> None:
    pyproject = ROOT / "pyproject.toml"
    if not pyproject.is_file():
        return

    text = read_text(pyproject)
    required_snippets = [
        '[project]',
        'name = "odoo-architect"',
        'odoo-architect = "odoo_architect_cli.cli:main"',
        'where = ["src"]',
    ]
    for snippet in required_snippets:
        if snippet not in text:
            fail(f"pyproject.toml missing CLI package metadata: {snippet}")


def check_no_generated_python_cache() -> None:
    for path in ROOT.rglob("__pycache__"):
        fail(f"Generated cache directory should not be committed: {rel(path)}")
    for path in ROOT.rglob("*.pyc"):
        fail(f"Generated bytecode should not be committed: {rel(path)}")


def check_python_syntax() -> None:
    for path in ROOT.rglob("*.py"):
        if any(part in {".git", ".venv", "__pycache__"} for part in path.parts):
            continue
        try:
            ast.parse(read_text(path), filename=str(path))
        except SyntaxError as exc:
            fail(f"Python syntax error in {rel(path)}: {exc}")


def parse_manifest(path: Path) -> dict:
    try:
        module = ast.parse(read_text(path), filename=str(path))
    except SyntaxError as exc:
        fail(f"Manifest syntax error in {rel(path)}: {exc}")
        return {}

    if not module.body or not isinstance(module.body[0], ast.Expr):
        fail(f"Manifest must contain a top-level dict expression: {rel(path)}")
        return {}

    try:
        manifest = ast.literal_eval(module.body[0].value)
    except (ValueError, SyntaxError) as exc:
        fail(f"Manifest must be a literal dict in {rel(path)}: {exc}")
        return {}

    if not isinstance(manifest, dict):
        fail(f"Manifest is not a dict: {rel(path)}")
        return {}

    return manifest


def python_files_with_model_classes(models_dir: Path) -> set[str]:
    result: set[str] = set()
    for path in models_dir.glob("*.py"):
        if path.name == "__init__.py":
            continue
        text = read_text(path)
        if re.search(r"^\s*_(inherit|name)\s*=", text, re.MULTILINE):
            result.add(path.stem)
    return result


def imported_model_modules(init_path: Path) -> set[str]:
    if not init_path.is_file():
        return set()

    imported: set[str] = set()
    for line in read_text(init_path).splitlines():
        stripped = line.strip()
        if not stripped.startswith("from . import "):
            continue
        names = stripped.split("import", 1)[1]
        imported.update(name.strip() for name in names.split(",") if name.strip())
    return imported


def declared_new_models(models_dir: Path) -> set[str]:
    models: set[str] = set()
    for path in models_dir.glob("*.py"):
        if path.name == "__init__.py":
            continue
        for match in re.finditer(r"^\s*_name\s*=\s*[\"']([^\"']+)[\"']", read_text(path), re.MULTILINE):
            models.add(match.group(1))
    return models


def access_csv_model_refs(path: Path) -> set[str]:
    if not path.is_file():
        return set()

    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames != ACCESS_HEADER:
            fail(f"Invalid ir.model.access.csv header in {rel(path)}")
            return set()
        return {row["model_id:id"] for row in reader if row.get("model_id:id")}


def check_manifest_and_addons() -> None:
    manifests = sorted(ROOT.glob("examples/**/__manifest__.py"))
    if not manifests:
        fail("No example Odoo addon manifests found under examples/")
        return

    for manifest_path in manifests:
        addon_dir = manifest_path.parent
        manifest = parse_manifest(manifest_path)
        if not manifest:
            continue

        missing = MANIFEST_REQUIRED_KEYS - set(manifest)
        if missing:
            fail(f"{rel(manifest_path)} missing manifest keys: {sorted(missing)}")

        depends = manifest.get("depends")
        if not isinstance(depends, list) or not all(isinstance(item, str) for item in depends):
            fail(f"{rel(manifest_path)} manifest 'depends' must be a list of strings")

        data_files = manifest.get("data")
        if not isinstance(data_files, list) or not all(isinstance(item, str) for item in data_files):
            fail(f"{rel(manifest_path)} manifest 'data' must be a list of strings")
            data_files = []

        for data_file in data_files:
            target = addon_dir / data_file
            if not target.is_file():
                fail(f"{rel(manifest_path)} references missing data file: {data_file}")

        view_index = next(
            (index for index, item in enumerate(data_files) if item.startswith("views/")),
            None,
        )
        security_index = next(
            (index for index, item in enumerate(data_files) if item == "security/ir.model.access.csv"),
            None,
        )
        if view_index is not None and security_index is not None and security_index > view_index:
            fail(f"{rel(manifest_path)} loads security after views")

        if manifest.get("installable") is not True:
            fail(f"{rel(manifest_path)} must set installable to True")

        if not (addon_dir / "README.md").is_file():
            fail(f"Addon is missing README.md: {rel(addon_dir)}")

        if not (addon_dir / "__init__.py").is_file():
            fail(f"Addon is missing __init__.py: {rel(addon_dir)}")

        models_dir = addon_dir / "models"
        if models_dir.is_dir():
            required_imports = python_files_with_model_classes(models_dir)
            actual_imports = imported_model_modules(models_dir / "__init__.py")
            missing_imports = required_imports - actual_imports
            if missing_imports:
                fail(
                    f"{rel(models_dir / '__init__.py')} does not import model files: "
                    f"{sorted(missing_imports)}"
                )

            access_path = addon_dir / "security" / "ir.model.access.csv"
            access_refs = access_csv_model_refs(access_path)
            for model_name in declared_new_models(models_dir):
                expected_ref = "model_" + model_name.replace(".", "_")
                if expected_ref not in access_refs:
                    fail(
                        f"New model {model_name} in {rel(models_dir)} lacks "
                        f"access rights ref {expected_ref}"
                    )

        all_python = "\n".join(read_text(path) for path in addon_dir.rglob("*.py"))
        if "opportunity_id" in all_python and "sale_crm" not in manifest.get("depends", []):
            fail(f"{rel(manifest_path)} uses sale.order opportunity_id but lacks sale_crm")

        if any(path.suffix == ".py" for path in addon_dir.rglob("*.py")):
            tests_dir = addon_dir / "tests"
            if not tests_dir.is_dir() or not (tests_dir / "__init__.py").is_file():
                fail(f"Addon with Python logic is missing tests package: {rel(addon_dir)}")


def check_xml_files() -> None:
    for path in ROOT.rglob("*.xml"):
        if any(part in {".git", ".venv", "__pycache__"} for part in path.parts):
            continue
        try:
            tree = ET.parse(path)
        except ET.ParseError as exc:
            fail(f"XML parse error in {rel(path)}: {exc}")
            continue

        root = tree.getroot()
        if "examples/custom_addons" in rel(path) and root.tag != "odoo":
            fail(f"Odoo XML file must have <odoo> root: {rel(path)}")

        text = read_text(path)
        fragile_patterns = ["//group[1]", "//page[1]", "//field[1]"]
        for pattern in fragile_patterns:
            if pattern in text:
                fail(f"Fragile XPath pattern {pattern!r} in {rel(path)}")


def check_skill_files() -> None:
    for path in [
        ROOT / ".codex/skills/odoo-architect/SKILL.md",
        ROOT / ".agents/skills/odoo-architect/SKILL.md",
    ]:
        if not path.is_file():
            fail(f"Missing skill file: {rel(path)}")
            continue
        text = read_text(path)
        if not text.startswith("---\n"):
            fail(f"Skill file lacks YAML frontmatter: {rel(path)}")
            continue
        parts = text.split("---", 2)
        if len(parts) < 3:
            fail(f"Skill file has incomplete YAML frontmatter: {rel(path)}")
            continue
        frontmatter = parts[1]
        if "name:" not in frontmatter or "description:" not in frontmatter:
            fail(f"Skill frontmatter must include name and description: {rel(path)}")


def main() -> int:
    check_required_files()
    check_cross_platform_scripts()
    check_cli_package_metadata()
    check_no_generated_python_cache()
    check_python_syntax()
    check_manifest_and_addons()
    check_xml_files()
    check_skill_files()

    if ERRORS:
        print("Production validation failed:\n")
        for error in ERRORS:
            print(f"- {error}")
        return 1

    print("Production validation passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
